---
- name: Install Apache
  hosts: all
  become: true
  tasks:
    - name: Install apache2 and php packages
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        update_cache: true
