---
- name: Install updates
  hosts: all
  become: true
  pre_tasks:
    - name: Install updates for Fedora
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Apply base configuration
  hosts: all
  become: true
  roles:
    - base

- name: Apply database server configuration
  hosts: db_servers
  become: true
  roles:
    - db_servers

- name: Apply web server configuration
  hosts: web_servers
  become: true
  roles:
    - web_servers
