---
- name: Install updates
  hosts: all
  become: true
  pre_tasks:
    - name: Install updates for Fedora
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Install site web server
  hosts: web_servers
  become: true
  tasks:
    - name: Install apache
      tags: apache, ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    - name: Copy html file to web server
      tags: apache, ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"

- name: Install site database
  tags: db, fedora
  hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb
      ansible.builtin.dnf:
        name: mariadb
      when: ansible_distribution == "Fedora"
