- name: Install Apache on web servers
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"

- name: Ensure Apache service is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: Change admin email address
  tags: apache, fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "Fedora"
  notify: Restart_Apache

- name: Copy HTML file for site
  tags: apache
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
